export const FETCH_COVID_DATA = 'FETCH_COVID_DATA';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const APPLY_SORT_SETTINGS = 'APPLY_SORT_SETTINGS';
export const FORMAT_COUNTRIES = 'FORMAT_COUNTRIES';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const OPEN_SORT_MODAL = 'OPEN_SORT_MODAL';
export const CLOSE_SORT_MODAL = 'CLOSE_SORT_MODAL';
